site_name: El blog de ASIR
site_url: https://tresespadas.github.io/andromeda/
site_author: Álvaro
site_description: El blog de ASIR
theme:
  name: material
  palette:
    - scheme: slate
      primary: indigo
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/images/logo.png
  favicon: assets/images/favicon.ico
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - search.highlight
    - search.suggest
extra_css:
  - assets/css/extra.css
nav:
  - Home: index.md
  - SRI:
      - Conectividad entre máquinas: SRI/conectividad.md
      - Proxmox:
        - Prerrequisitos: SRI/proxmox/prerequisitos.md
        - Cluster: SRI/proxmox/cluster.md
        - NAS: SRI/proxmox/nas.md
        - HA: SRI/proxmox/alta_disponibilidad.md
  - ASO:
      - Pasos previos: ASO/pasos_previos.md
      - LDAP:
        - Configuración LDAP Servidor: ASO/ldap/configuracion_ldap_servidor.md
        - Configuración LDAP Cliente: ASO/ldap/configuracion_ldap_cliente.md
      - Samba:
        - Configuración Samba desde Ubuntu Server: ASO/samba/instalacion_samba.md
        - Configuración Samba desde Ubuntu Desktop: ASO/samba/instalacion_samba2.md
      - NFS:
        - Configuración NFS: ASO/nfs/instalacion_nfs.md
      - Windows Server:
        - Instalación y configuración AD: ASO/wserver/instalacion_configuracion_dominio_ad.md
  - Proyecto:
      - Fase 1: Proyecto/fase1.md
      - Fase 2: Proyecto/fase2.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
plugins:
  - search
